name: globee
description: "Globee - The Next Generation of Short Videos Platform"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  audioplayers: ^6.4.0
  better_player_plus: ^1.0.8
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^19.2.1
  flutter_localization: ^0.3.2
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.12
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  googleapis_auth: ^2.0.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  pinput: ^5.0.1
  provider: ^6.1.5
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  timeago: ^3.7.1
  url_launcher: ^6.3.1
  video_compress: ^3.1.4
  webview_flutter: ^4.13.0
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/sounds/like.mp3
    - shorebird.yaml
    - .env
